READ WRITE:C146(*)

ALL RECORDS:C47([XUtilisateurs:2])
DELETE SELECTION:C66([XUtilisateurs:2])

ALL RECORDS:C47([XFonctions:3])
DELETE SELECTION:C66([XFonctions:3])

ALL RECORDS:C47([XProfils:4])
DELETE SELECTION:C66([XProfils:4])

ALL RECORDS:C47([XDroits:7])
DELETE SELECTION:C66([XDroits:7])

READ ONLY:C145(*)