C_LONGINT:C283($C;$L)
LISTBOX GET CELL POSITION:C971(*;"ListBoxPrest";$C;$L)
If ($L>0)
	DELETE FROM ARRAY:C228(Colonne1;$L)
	DELETE FROM ARRAY:C228(Colonne2R;$L)
	DELETE FROM ARRAY:C228(Colonne3R;$L)
	DELETE FROM ARRAY:C228(CodePrestation;$L)
	DELETE FROM ARRAY:C228(AnnéePrestation;$L)
End if 